name: Publish Docker images

on:
  push:
    branches:
      - '**'
  release:
    types: [released, prereleased]

jobs:
  docker:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [bnkr]
        include:
          - image: bnkr
            file: Dockerfile
            context: "."
            tag: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        if: matrix.image == 'bnkr'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: matrix.image == 'bnkr'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: engrmth
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image(s)
        if: matrix.image == 'bnkr'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: engrmth/${{ matrix.image }}:${{ matrix.tag }}
      - name: Build and push image(s)
        if: matrix.image != 'bnkr'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/${{ matrix.file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: engrmth/${{ matrix.image }}:${{ matrix.tag }}